### ISSUE TITLE
Crash when Flow Launcher is installed with scoop

### ISSUE THREAD

**Issue by LeLocTai** [Garulf/Flox#12]
Flow Launcher is installed with scoop folder name is `Flow-Launcher`, with a dash and not a space. This make Flox crash on import.

**Comment by Garulf** [comment]
Hi @LeLocTai ! Sorry about that fixing Scoop was brought to my attention but I havent had a chance to properly fix it yet. It's very much on my todo list though.

**Comment by Garulf** [comment]
Fixed: https://github.com/Garulf/Flox/pull/13

**Comment by LeLocTai** [comment]
Doesn't work for me until I capitalize SCOOP_FLOW_LAUNCHER_DIR_NAME. Since it's Windows we should normalize the case anyway

**Comment by Garulf** [comment]
I realized this after I pushed. What's causing the folder name to be different between users?

EDIT: Could you provide your path so I can test against?

**Comment by Garulf** [comment]
Should be fixed in https://github.com/Garulf/Flox/pull/14
