### ISSUE TITLE
Opening file default encoding error

### ISSUE THREAD

**Issue by ThisGoLive** [Garulf/Flox#17]
OS：Windows 10
Python Version: 3.11
Flox Version : 0.19.3

When I was developing the plug-in for Flow Launcher, there was an error reading Setting.json

Erro:  UnicodeDecodeError: 'xxx' codec can't decode byte 0xae in position 170: illegal multibyte sequence

The system default encoding cannot open utf-8. 
 flox/_init__.py  line 213 - 214: 
        with open(os.path.join(self.plugindir, PLUGIN_MANIFEST), 'r') as f:
            return json.load(f)

I need to change my Setting.json to system default encoding ,To solve this problem.

Maybe you can add an encoding  parameter to the error location,

**Comment by Garulf** [comment]
Sorry about that. I'll add the relevant code to the next patch release later tonight.

**Comment by Garulf** [comment]
Fixed with version `0.19.4`.
